name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - transformers
    - torch>=2.0
    - torchvision
    - datasets
    - requests
    - cython
    - distributed
    - matplotlib
    - numba
    - xgboost
    - pandas
    - pillow
    - memory_profiler
    - line_profiler
    - scikit-learn
    - plotly
    - scipy
    - numpy
    - boto
    - scikit-image
    - jupyter
    - tqdm